#config for sc_50_nexus_api.sh

TIMEOUT=30
RETRIES=1

CHECKTOOL=curl

# one NEXUS PGWY instance to test enrollment against
 NEXUS_API_APIBASE[0]="https://192.168.0.1:8444"
 NEXUS_API_P12FILE[0]="/opt/syscheck/cert/test.p12"
 NEXUS_API_P12PASSWORD[0]="1234"
 NEXUS_API_JAVA_CLASSPATH[0]="/opt/syscheck/lib:/opt/syscheck/lib/*" 
 NEXUS_API_JAVA_CLASS[0]="PgwySign"
 NEXUS_API_CACHAIN[0]="/opt/syscheck/cert/nexus-ca-bundle.pem"
#
#
# NEXUS_API_APIBASE[1]="https://192.168.0.2:8444"
# NEXUS_API_P12FILE[1]="../cert/officer2.p12"
# NEXUS_API_P12PASSWORD[1]="changeit"
# NEXUS_API_JAVA_CLASSPATH[1]="/opt/syscheck/lib:/opt/syscheck/lib/*" 
# NEXUS_API_JAVA_CLASS[1]="PgwySign"
# NEXUS_API_CACHAIN[1]="../cert/nexus-ca-bundle2.pem"

